name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write        # Add this for label creation
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: java-sdk/.release-please-config.json
          manifest-file: java-sdk/.release-please-manifest.json

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    strategy:
      matrix:
        path: ${{ fromJson(needs.release-please.outputs.paths_released) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Update dependency versions
        run: |
          # Update inter-module dependencies to use released versions
          # This script will be run for each module that was released
          MODULE_PATH="${{ matrix.path }}"
          
          if [ -f "$MODULE_PATH/pom.xml" ]; then
            echo "Processing module at $MODULE_PATH"
            
            # Get the new version from the POM
            cd "$MODULE_PATH"
            NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            MODULE_ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
            
            echo "Module $MODULE_ARTIFACT released with version $NEW_VERSION"
            
            # Update dependencies in other modules to use this new version
            cd ../../..
            find java-sdk/packages -name "pom.xml" -not -path "$MODULE_PATH/*" | while read pom; do
              echo "Checking $pom for dependencies on $MODULE_ARTIFACT"
              if grep -q "<artifactId>$MODULE_ARTIFACT</artifactId>" "$pom"; then
                echo "Updating dependency in $pom"
                # Use xmlstarlet or sed to update the version
                # This is a simplified approach - you might need more sophisticated XML handling
                mvn versions:use-dep-version \
                  -Dincludes=com.yourcompany:$MODULE_ARTIFACT \
                  -DdepVersion=$NEW_VERSION \
                  -DforceVersion=true \
                  -f "$pom" || true
              fi
            done
          fi
          
      - name: Build and test
        run: |
          cd "${{ matrix.path }}"
          mvn clean verify
          
      - name: Publish to GitHub Packages
        run: |
          cd "${{ matrix.path }}"
          mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Update snapshot versions after release
  update-snapshots:
    runs-on: ubuntu-latest
    needs: [release-please, publish]
    if: needs.release-please.outputs.releases_created == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Update inter-module dependencies
        run: |
          # After all modules are released, update any remaining snapshot dependencies
          # to use the latest released versions
          
          PATHS_RELEASED='${{ needs.release-please.outputs.paths_released }}'
          echo "Released paths: $PATHS_RELEASED"
          
          # For each released module, update dependencies in other modules
          echo "$PATHS_RELEASED" | jq -r '.[]' | while read module_path; do
            if [ -f "$module_path/pom.xml" ]; then
              cd "$module_path"
              MODULE_ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
              NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              cd ../../..
              
              # Update this dependency in all other modules
              find java-sdk/packages -name "pom.xml" -not -path "$module_path/*" | while read pom; do
                if grep -q "<artifactId>$MODULE_ARTIFACT</artifactId>" "$pom"; then
                  mvn versions:use-dep-version \
                    -Dincludes=com.yourcompany:$MODULE_ARTIFACT \
                    -DdepVersion=$NEW_VERSION \
                    -DforceVersion=true \
                    -f "$pom" || true
                fi
              done
            fi
          done
          
      - name: Commit dependency updates
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add -A
            git commit -m "chore: update inter-module dependencies after release"
            git push origin main
          fi